language: android

jdk:
  - oraclejdk8

env:
    global:
        - NDK_VERSION=r12b
        - NDK_CCACHE=ccache
        - ARCH=`uname -m`
        - GOROOT_BOOTSTRAP=$GOROOT
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - SBT=$HOME/.android/sbt
        - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

scala:
    - 2.11.8

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

install:
    - mkdir -p $HOME/.android
    - pushd $HOME/.android
    - >
      if [ ! -d "$ANDROID_NDK_HOME" ]; then
          mkdir -p $ANDROID_NDK_HOME;
          wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
      fi
    - >
      if [ ! -f "$SBT" ]; then
          curl -o $HOME/.android https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt;
          chmod a+x $SBT;
      fi
    - popd

script:
    - cp local.properties.travis local.properties
    - $SBT native-build android:package-release
